/**
 * Launch gate §10.4 — "Ref normalizer rejects/normalizes the variant-spelling
 * test set." This is that gate, run in CI: every row of the audited acceptance
 * set is pushed through the real normalizeRef and checked.
 *
 * The set was generated by a design workflow and then AUDITED by hand (gematria
 * math, daf ranges, canonical spellings) before adoption — it is not trusted
 * machine output. It currently covers the implemented grammars (Talmud +
 * Tanach); Mishnah/Rambam/Shulchan Aruch rows are added as those slices land,
 * and ranges + prose-embedded refs are deferred out of V1.
 *
 * A NORMALIZED row asserts the exact canonical ref (and Hebrew ref when given);
 * a REJECTED row asserts only that it is refused — the specific error code is a
 * finer contract the focused unit tests pin, not the gate.
 */
import { describe, expect, it } from "vitest";

import { normalizeRef } from "./normalize";

import fixture from "./acceptance.fixture.json";

type Row =
  | { input: string; status: "normalized"; ref: string; heb?: string }
  | { input: string; status: "rejected" };

const rows = fixture.rows as Row[];
const normalized = rows.filter((r): r is Extract<Row, { status: "normalized" }> => r.status === "normalized");
const rejected = rows.filter((r) => r.status === "rejected");

describe("§10.4 acceptance set — normalizes variant spellings", () => {
  it("has a substantial set (guards against an empty or truncated fixture)", () => {
    // A gate that silently ran zero rows would be the worst kind of green.
    expect(normalized.length).toBeGreaterThanOrEqual(50);
    expect(rejected.length).toBeGreaterThanOrEqual(15);
  });

  it.each(normalized.map((r) => [r.input, r.ref, r.heb] as const))(
    "%s → %s",
    (input, ref, heb) => {
      const r = normalizeRef(input);
      expect(r.ok, `expected "${input}" to normalize, got ${r.ok ? "" : r.error.code}`).toBe(true);
      if (r.ok) {
        expect(r.value.normalizedRef).toBe(ref);
        if (heb) expect(r.value.hebrewRef).toBe(heb);
      }
    },
  );
});

describe("§10.4 acceptance set — rejects malformed and invalid refs", () => {
  it.each(rejected.map((r) => [r.input] as const))("%j rejects", (input) => {
    expect(normalizeRef(input).ok, `expected "${input}" to be rejected`).toBe(false);
  });
});
